Add files via upload
DeveLeb/Develeb-Platform pull request #13
Opened 2024-06-21 07:30 UTC by itsTony4dev

2024-06-24 16:48 UTC, Hkataya requested changes

2024-06-24 16:48 UTC, Hkataya commented on Data Model For Job Entity.sql
> +  "category_id" INTEGER PRIMARY KEY,
i would keep the naming simple here. We already know the table name is Job_Category, we can name the columns id and title

2024-06-24 16:48 UTC, Hkataya commented on Data Model For Job Entity.sql
> +  "total_views" INTEGER,
why is total_views added here?

2024-06-25 09:29 UTC, Sami-Sh99 requested changes

2024-06-25 09:29 UTC, Sami-Sh99 commented on Data Model For Job Entity.sql
> +  "location" VARCHAR,
- [ ] give all VARCHARs a limit

2024-06-28 14:56 UTC, Sami-Sh99 requested changes

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +  title: Job Board API - OpenAPI 3.0
Remove ` - OpenAPI 3.0`

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +  description: This is a Job Board API based on the OpenAPI 3.0 specification.
`Job Board RESTful API based on the OpenAPI 3.0 specification. It includes CRUD methods and filtering capabilities for managing job postings.`

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +    email: apiteam@jobboard.com
remove email

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +  - url: https://jobboard.api.com/v1
remove servers

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +    description: Everything about jobs
`User Priviledged Operations`

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +    description: Admin operations
`Admin privileged Operations`

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +  /job/{jobId}:
`/jobs/{jobId}`

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +      summary: Get job by ID
let's stay consistent, either `ID` or `Id`

I suggest `Id`

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +      description: Returns a single job
`Returns a job of the given Id`

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +          description: Successful operation
just `success` all lowercase

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +          description: Invalid ID supplied
`invalid Id supplied`

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +          description: Job not found
lowercase

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +  /jobs:
This should be the first element in the list (before /job/{jobId})

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +  /job/{jobId}:
path should start in plural `jobs` fix it for the whole file

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +    put:
add a `PATCH` method too

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +      summary: Delete a particular job
... by Id

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +      summary: Get jobs with filters
`... with optional filters`

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +          description: No jobs found for the given filters
or there are no jobs? filters are not always provided

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +  /job/submit:
drop the /submit
POST /jobs already refers that a job is submitted for creation

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +          description: Job submitted for approval
`job submitted successfully, pending approval`

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +  /job/{jobId}/approve:
drop this endpoint
Admin will just send a POST /jobs/id with the approval state

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +  /job/{jobId}/reject:
drop this too

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +  /jobcategories:
Missing other crud operations (GET, PUT, DELETE)

2024-06-28 14:56 UTC, Sami-Sh99 commented on jobAPI_swagger.yaml
> +  /joblevels:
Missing other crud operations (GET, PUT, DELETE)

2024-07-03 13:38 UTC, merged