Farida resource db model
DeveLeb/Develeb-Platform pull request #16
Opened 2024-06-23 13:26 UTC by faridaalamine2

2024-06-24 16:50 UTC, Hkataya requested changes

2024-06-24 16:50 UTC, Hkataya commented on resource_data_model.sql
> +  "resourceId" integer PRIMARY KEY,
We can keep the naming simple and just name it id

2024-06-24 16:50 UTC, Hkataya commented on resource_data_model.sql
> +  "viewId" integer PRIMARY KEY,
let's use snake case as convention. viewId -> view_id

2024-06-24 16:50 UTC, Hkataya commented on resource_data_model.sql
> +  "view_count" integer DEFAULT 0,
Why do we need view_count here?

2024-06-24 16:58 UTC, Sami-Sh99 commented on resource_data_model.sql
> +  "link" varchar(1000) NOT NULL,
a 1000 character for a link is a lot no? how about 255?

2024-06-24 17:00 UTC, Sami-Sh99 commented on resource_data_model.sql
> +  "tags" varchar(255)[],
tags will be redundant between the resources, create a tag table (id, tag_name) and store the reference id here

2024-06-30 16:27 UTC, Sami-Sh99 approved these changes
Looks good to me, please fix the minor changes before merging 

Make sure to squash the commits so that one commit is merged to master

2024-06-30 16:27 UTC, Sami-Sh99 commented on resource_api_endpoints.yaml
> +          description: successful operation
'success'

2024-06-30 16:27 UTC, Sami-Sh99 commented on resource_api_endpoints.yaml
> +    post:
I don't think a post method is required
Since with each get request the user will do, the backend service will handle incrementing the value

2024-06-30 17:16 UTC, Hkataya approved these changes

2024-07-01 09:50 UTC, merged