Company SQL models and Swagger API docs
DeveLeb/Develeb-Platform pull request #18
Opened 2024-06-23 19:45 UTC by the-refrigerator

Relevant issues:

- [Design API Endpoints for Company Entities](https://github.com/DeveLeb/Develeb-WebApp/issues/9)
- [Design Data Model for Company Entities](https://github.com/DeveLeb/Develeb-WebApp/issues/5)

2024-06-24 16:46 UTC, Hkataya requested changes

2024-06-24 16:46 UTC, Hkataya commented on ahmad-company-db-model.sql
> +CREATE TABLE "Company_Social_Platform" (
Why did you split the social platforms to another table? wouldn't it be simpler to store them in the same table:
- intagram_url
- facebook_url 
- .....

2024-06-24 16:46 UTC, Hkataya commented on ahmad-company-db-model.sql
> +  "companyId" integer,
Let's keep the naming consistent and have everything in snake case. companyId -> company_id

2024-06-24 17:02 UTC, Sami-Sh99 commented on ahmad-company-db-model.sql
> +  "hidden" BOOLEAN dEFAULT false,
dEFAULT -> DEFAULT

2024-06-24 17:04 UTC, Sami-Sh99 commented on ahmad-company-db-model.sql
> +  "hidden" BOOLEAN dEFAULT false,
please apply this change to all the file, it's redundant

2024-06-24 17:05 UTC, Sami-Sh99 commented on ahmad-company-db-model.sql
> +  "typeId" VARCHAR,
let's stick to snake typeId -> type_id

2024-06-24 17:11 UTC, Sami-Sh99 commented on ahmad-company-db-model.sql
> +  "type" VARCHAR UNIQUE,
identify the varchar's length, otherwise, it will take the default max length (65535) which is really huge store capacity..

2024-06-24 17:12 UTC, Sami-Sh99 commented on ahmad-company-db-model.sql
> +  "companyId" integer,
integer -> INTEGER

2024-06-24 17:15 UTC, Sami-Sh99 commented on ahmad-company-db-model.sql
> +CREATE TABLE "User" ( -- This is a placeholder for the user table
This PR should not be merged before merging branch #15

2024-06-24 19:22 UTC, the-refrigerator commented
Everything should be fixed in [commit 4ace5d907800f73f838a8705ae5d8aeec74987c4](https://github.com/DeveLeb/Develeb-Platform/pull/18/commits/4ace5d907800f73f838a8705ae5d8aeec74987c4)

2024-06-30 16:45 UTC, Hkataya approved these changes

2024-06-30 16:50 UTC, Hkataya commented on ahmad-company-db-model.sql
> +  "twitter_url" TEXT,
i would change this to "x_url". We don't wanna piss Elon off 😆

2024-07-03 13:38 UTC, merged