Drizzle
DeveLeb/Develeb-Platform pull request #34
Opened 2024-07-10 18:03 UTC by itsTony4dev

2024-07-12 10:09 UTC, Hkataya requested changes

2024-07-12 10:09 UTC, Hkataya commented on packages/backend/src/drizzle/schema.ts
> +    eventDateIdx: index('event_date_idx').on(table.date),
Why are we indexing event date

2024-07-12 10:09 UTC, Hkataya commented on packages/backend/src/drizzle/schema.ts
> +    eventTypeIdx: index('event_type_idx').on(table.typeId),
Same here, i would add a fulltext index to event title maybe but not the rest

2024-07-12 10:09 UTC, Hkataya commented
general comments:

- Move all the files into a folder named db. 
- The file named db rename to index.ts

2024-07-12 10:24 UTC, itsTony4dev commented on packages/backend/src/drizzle/migrations/meta/_journal.json
> +{
typically keeps track of which migrations have been applied to the database. it's crucial for maintaining the state of database schema.
Without this file you might risk data integrity issues if migrations are run out of order or duplicated.

2024-07-15 16:30 UTC, Hkataya requested changes

2024-07-15 16:30 UTC, Hkataya commented on packages/backend/drizzle.config.ts
@itsTony4dev Seems like we didnt use this config anywhere ?

2024-07-15 16:30 UTC, Hkataya commented on packages/backend/drizzle.config.ts
> +import * as dotenv from 'dotenv';
Also Rename drizzle folder to db. And db file to index

2024-07-17 10:55 UTC, Hkataya approved these changes

2024-07-17 10:56 UTC, merged