job api updated
DeveLeb/Develeb-Platform pull request #41
Opened 2024-07-17 12:11 UTC by itsTony4dev

job views added at the end of the jobs routes

2024-07-17 12:14 UTC, itsTony4dev commented on docs/api-docs.yaml
> +  /jobs/{id}/views:
I added this route

2024-07-17 18:24 UTC, Hkataya requested changes

2024-07-17 18:24 UTC, Hkataya commented on docs/api-docs.yaml
> +                  type: object
Wrap your response with the data object. Check this example: https://develeb.github.io/Develeb-Platform/#/job/getJobById

Also rename resource_Id to job_id

2024-07-22 15:33 UTC, Hkataya approved these changes

2024-07-22 15:33 UTC, merged